{%- import 'addressable.sv' as addressable with context -%}

`define ST(x) `"x`"
`define CHECK_EQUAL(val, exp) \
    assert(exp==val) else $fatal(1, "\n\t%s == %s: 0x%0h != 0x%0h\n", `ST(val), `ST(exp), val, exp);

`define HW_WRITE(name, idx, val) \
            ``name``_we``idx <= 1'b1; \
            ``name``_wdata``idx <= val; \
            @(posedge clk); \
            ``name``_we``idx <= '0;


// This file was autogenerated by PeakRDL-verilog
`include "timescale.vh"

module {{get_inst_name(top_node)}}_wrapper_tb;

`include "spi_ctrl_defines.vh"
`include "chip_defines.vh"

  reg rst;
  reg clk;
  reg spi_clk;
  reg i_spi_ssn;
  reg i_spi_mosi;
  reg spi_ssn;
  reg spi_mosi;
  wire spi_miso;
  reg [7:0] rdata;

  integer   i;
  
  task spi_write;
    input [7:0] addr;
    input [7:0] data;
    
    begin
      integer 		     i;
      
      i_spi_ssn <= 0;
      
      for (i = 0; i < 24; i = i + 1) begin
	if (i < 8)
	  i_spi_mosi <= CMD_WRITE[7-i];
	else if (i < 16)
	  i_spi_mosi <= addr[15-i];
	else
	  i_spi_mosi <= data[23-i];
	
	@(posedge spi_clk);
      end

      i_spi_ssn <= 1;

      for (i = 0; i < 4; i = i + 1) begin
	@(posedge clk);
      end
    end    
  endtask // spi_write

  task spi_read;
    input [7:0] addr;
    output reg [7:0] rdata;

    begin
      integer 		     i;

      i_spi_ssn <= 0;
      rdata = 8'd0;
      
      for (i = 0; i < 24; i = i + 1) begin
	if (i < 8)
	  i_spi_mosi <= CMD_READ[7-i];
	else if (i < 16)
	  i_spi_mosi <= addr[15-i];

	@(posedge spi_clk);
	
	if (i >= 16)
	  rdata = {rdata[6:0], spi_miso};

      end // for (i = 0; i < 24; i = i + 1)
      
      i_spi_ssn <= 1;

      for (i = 0; i < 4; i = i + 1) begin
	@(posedge clk);
      end
    end    
  endtask // spi_read
  
  // Register map signals
{%- for node in top_node.descendants() -%}
{%- if isinstance(node, FieldNode) -%}
 {%- if node is hw_writable and node is not internal %}
    logic {{node.parent|full_array_ranges}}[{{node|bit_range}}] {{signal(node)}};
 {%- endif -%}
 {%- if node is hw_readable and node is not internal %}
    logic {{node.parent|full_array_ranges}}[{{node|bit_range}}] {{signal(node)}};

 {%- endif -%}
{%- endif -%}
{%- endfor %}

  initial begin
    clk <= 1'b0;
    forever #10 clk <= ~clk;
  end

  assign spi_clk = ~spi_ssn & clk;
  
  initial begin
    rst <= 0;
    for (i = 0; i < 4; i = i + 1) begin
      @(posedge clk);
    end
    
    rst <= 1;
    i_spi_ssn <= 1;
    i_spi_mosi <= 0;

    for (i = 0; i < 4; i = i + 1) begin
      @(posedge clk);
    end
    rst <= 0;
    $display("%t: TB: reset complete", $time());
  end

  always @(negedge clk) begin
    spi_ssn <= i_spi_ssn;
    spi_mosi <= i_spi_mosi;    
  end
  
  digital_wrapper digital_wrapper_inst
    (
     .*
     );

  initial begin
    logic [7:0] temp;
    logic [7:0] value;

    for (i = 0; i < 4; i = i + 1) begin
      @(posedge clk);
    end
    // init all hw inputs
{%- for node in top_node.descendants() -%}
{%- if isinstance(node, FieldNode) %}
{%- if node is hw_writable and node is not internal %}
    {{signal(node)}} <= '0;
{%- endif -%}
{%- endif -%}
{%- endfor %}

    @(negedge rst);


{%- for node in top_node.descendants(unroll=True) -%}
{%- if isinstance(node, FieldNode) %}
        $display("%t: Testcase ({{signal(node)}} {{full_idx(node.parent)}}):", $time());
    {%- if node is hw_writable and node is not internal %}
        $display("%t:\tHardware write test", $time());
        for (int IDX = {{node.lsb}}; IDX <= {{node.msb}}; ++IDX) begin

            `HW_WRITE( {{signal(node)}}, {{full_idx(node.parent)}}, (1 << (IDX-{{node.lsb}})) )
	    spi_read({{node.parent.absolute_address}}, rdata);
            `CHECK_EQUAL(rdata[{{node|bit_range}}], (1 << (IDX-{{node.lsb}})))
            `HW_WRITE( {{signal(node)}}, {{full_idx(node.parent)}}, 0 )
	    spi_read({{node.parent.absolute_address}}, rdata);
            `CHECK_EQUAL(rdata[{{node|bit_range}}], 0)

        end
    {%- endif -%}
    {%- if node is hw_readable and node.is_sw_writable and node is not internal %}
        $display("%t:\tSoftware write (hardware read) test", $time());
        for (int IDX = {{node.lsb}}; IDX <= {{node.msb}}; ++IDX) begin

            temp = '0;
            temp[{{node|bit_range}}] = {{signal(node)}}{{full_idx(node.parent)}};
        {%- if node.get_property('onwrite') == OnWriteType.woset %}
            temp[IDX] = 1;
            value = temp;
        {%- elif node.get_property('onwrite') == OnWriteType.woclr %}
            temp[IDX] = 0;
            value = temp;
        {%- elif node.get_property('onwrite') == OnWriteType.wot %}
            temp[IDX] = !temp[IDX];
            value = temp;
        {%- elif node.get_property('onwrite') == OnWriteType.wzs %}
            temp = '1;
            temp[IDX] = {{signal(node)}}{{full_idx(node.parent)}}[IDX];
            value = '1;
        {%- elif node.get_property('onwrite') == OnWriteType.wzc %}
            temp = '0;
            temp[IDX] = {{signal(node)}}{{full_idx(node.parent)}}[IDX];
            value = '0;
        {%- elif node.get_property('onwrite') == OnWriteType.wzt %}
            temp = ~temp;
            temp[IDX] = {{signal(node)}}{{full_idx(node.parent)}}[IDX];
            value = ~temp;
        {%- elif node.get_property('onwrite') == OnWriteType.wclr %}
            temp = '0;
            value = '0;
        {%- elif node.get_property('onwrite') == OnWriteType.wset %}
            temp = '1;
            value = '1;
        {%- else %}
            temp = (1 << IDX);
            value = '0;
        {%- endif %}
	    spi_write({{node.parent.absolute_address}}, (1 << IDX) );
            @(posedge clk) `CHECK_EQUAL({{signal(node)}}{{full_idx(node.parent)}}, temp[{{node|bit_range}}])

	    spi_write({{node.parent.absolute_address}}, 0);
            @(posedge clk) `CHECK_EQUAL({{signal(node)}}{{full_idx(node.parent)}}, value[{{node|bit_range}}])

        end
    {%- endif -%}
    {%- if node.is_sw_readable and node.is_sw_writable %}
        $display("%t:\tSoftware write (software read) test", $time());
        for (int IDX = {{node.lsb}}; IDX <= {{node.msb}}; ++IDX) begin

            temp = '0;
	    spi_read({{node.parent.absolute_address}}, rdata);
            temp[{{node|bit_range}}] = rdata[{{node|bit_range}}];
        {%- if node.get_property('onwrite') == OnWriteType.woset %}
            temp[IDX] = 1;
            value = temp;
        {%- elif node.get_property('onwrite') == OnWriteType.woclr %}
            temp[IDX] = 0;
            value = temp;
        {%- elif node.get_property('onwrite') == OnWriteType.wot %}
            temp[IDX] = !temp[IDX];
            value = temp;
        {%- elif node.get_property('onwrite') == OnWriteType.wzs %}
            temp = '1;
            temp[IDX] = {{signal(node)}}{{full_idx(node.parent)}}[IDX];
            value = '1;
        {%- elif node.get_property('onwrite') == OnWriteType.wzc %}
            temp = '0;
            temp[IDX] = {{signal(node)}}{{full_idx(node.parent)}}[IDX];
            value = '0;
        {%- elif node.get_property('onwrite') == OnWriteType.wzt %}
            temp = ~temp;
            temp[IDX] = {{signal(node)}}{{full_idx(node.parent)}}[IDX];
            value = ~temp;
        {%- elif node.get_property('onwrite') == OnWriteType.wclr %}
            temp = '0;
            value = '0;
        {%- elif node.get_property('onwrite') == OnWriteType.wset %}
            temp = '1;
            value = '1;
        {%- else %}
            temp = (1 << IDX);
            value = '0;
        {%- endif %}

	    spi_write({{node.parent.absolute_address}}, (1 << IDX) );
	    spi_read({{node.parent.absolute_address}}, rdata);
            `CHECK_EQUAL(rdata[{{node|bit_range}}], temp[{{node|bit_range}}])

	    spi_write({{node.parent.absolute_address}}, 0);
	    spi_read({{node.parent.absolute_address}}, rdata);
            `CHECK_EQUAL(rdata[{{node|bit_range}}], value[{{node|bit_range}}])

        end
    {%- endif -%}
{%- endif -%}
{%- endfor %}

        #200;
        $display("%t: TB: test complete", $time());
        $display("\n\t\t===================");
        $display(  "\t\t=   TEST PASSED   =");
        $display(  "\t\t===================\n");
        $finish();
    end

endmodule

